-- liquibase formatted sql


-- changeset gleb:dog1
CREATE TABLE dog (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(50) NOT NULL,
is_male BOOLEAN NOT NULL,
breed VARCHAR(50) NOT NULL,
weight REAL NOT NULL,
date_of_birth TIMESTAMP WITH TIME ZONE NOT NULL,
file_size BIGINT,
media_type VARCHAR(50),
photo BYTEA,
path_to_file TEXT,
description TEXT NOT NULL,
special_needs TEXT NOT NULL,
owner_id BIGINT,
status SMALLINT,
CONSTRAINT dog_pk PRIMARY KEY (id),
CONSTRAINT "FK_dog_owner" FOREIGN KEY (owner_id) REFERENCES owner(id)
);
