-- liquibase formatted sql


-- changeset volkov:1
CREATE TABLE pet (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(50) NOT NULL,
breed VARCHAR(50) NOT NULL,
weight REAL NOT NULL,
age INTEGER NOT NULL,
photo BYTEA NOT NULL,
path_to_file TEXT NOT NULL,
description TEXT NOT NULL,
special_needs TEXT NOT NULL
 );
ALTER TABLE pet ADD CONSTRAINT pet_pk PRIMARY KEY (id);
ALTER TABLE pet ADD owner_id BIGINT;

-- changeset tav:4
alter table pet add constraint "FK_pet_owner" foreign key (owner_id) references owner(id);

-- changeset volkov:7
ALTER TABLE pet DROP COLUMN age;
ALTER TABLE pet ADD
date_of_birth TIMESTAMP WITH TIME ZONE NOT NULL;
