-- liquibase formatted sql


-- changeset volkov:5
CREATE TABLE reports(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
owner_id BIGINT NOT NULL,
pet_id BIGINT NOT NULL,
file_size BIGINT,
media_type VARCHAR(50),
photo BYTEA,
path_to_file TEXT,
feeding_report TEXT NOT NULL,
date_of_report TIMESTAMP WITH TIME ZONE NOT NULL,
general_report TEXT NOT NULL,
behavior_report TEXT NOT NULL,
CONSTRAINT reports_pk PRIMARY KEY (id),
CONSTRAINT "FK_reports_owner" FOREIGN KEY (owner_id) REFERENCES owner(id),
CONSTRAINT "FK_reports_pet" FOREIGN KEY (pet_id) REFERENCES pet(id)
);

