-- liquibase formatted sql


-- changeset volkov:5
CREATE TABLE reports(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
owner_id BIGINT NOT NULL,
pet_id BIGINT NOT NULL,
file_size BIGINT,
media_type VARCHAR(50),
photo BYTEA,
path_to_file TEXT,
feeding_report TEXT NOT NULL,
date_of_report TIMESTAMP WITH TIME ZONE NOT NULL,
general_report TEXT NOT NULL,
behavior_report TEXT NOT NULL,
CONSTRAINT reports_pk PRIMARY KEY (id),
CONSTRAINT "FK_reports_owner" FOREIGN KEY (owner_id) REFERENCES owner(id),
CONSTRAINT "FK_reports_pet" FOREIGN KEY (pet_id) REFERENCES pet(id)
);

 -- changeset tav:51
 ALTER TABLE reports
 DROP CONSTRAINT "FK_reports_pet",
 DROP COLUMN pet_id,
 ADD COLUMN cat_id BIGINT,
 ADD COLUMN dog_id BIGINT,
 ADD COLUMN apm BIGINT NOT NULL,
 ADD CONSTRAINT "FK_reports_apm" FOREIGN KEY (apm) REFERENCES adoption_process_monitor(id),
 ADD CONSTRAINT "FK_reports_cat" FOREIGN KEY (cat_id) REFERENCES cat(id),
 ADD CONSTRAINT "FK_reports_dog" FOREIGN KEY (dog_id) REFERENCES dog(id)